config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  
  
  # config/routes.rb
  get '/search_by_location', to: 'home#search_by_location', as: 'search_by_location'

  
  get 'user_dashboard', to: 'users#dashboard', as: :user_dashboard
  get '/users/profile', to: 'users#profile', as: :user_profile
  get '/shops/profile', to: 'shops#profile'
  
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show]

  resources :items do
    post 'favorites', to: 'favorites#create', on: :member
  end
  
  resources :favorites, only: [:create, :destroy]

  resources :users do
    member do
      get :dashboard
      get :shop_new, to: 'shops#new', as: :user_shop_new
      post :shop_create, to: 'shops#create', as: :user_shop_create
      get :item_new, to: 'items#new', as: :user_item_new
    end
  end

  resources :shops do
    resources :events #
    resources :items, only: [:new, :create] 
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
 
  has_many :shops
  has_many :items
  
  has_many :favorites
  has_many :favorited_items, through: :favorites, source: :item

  serialize :roles, Array
  
  attr_accessor :custom_field
  
  after_initialize :initialize_roles

  def initialize_roles
    self.roles ||= []
  end

  def add_role(role)
    self.roles ||= []
    self.roles << role unless self.roles.include?(role)
  end

  def remove_role(role)
    self.roles -= [role]
  end

  def has_role?(role)
    self.roles.include?(role.to_s)
  end

  def customer?
    has_role?("customer") # メソッド内でroleではなくhas_role?メソッドを使用する
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    if current_user
      if current_user.has_role?(:vendor)
        # ベンダーの場合は user_dashboard ビューを表示
        @locations = Location.all
        @shops = Shop.where(user_id: current_user.id)
        @items = Item.where(user_id: current_user.id)
        render 'users/dashboard'
      else
        # 一般ユーザーの場合は home/index ビューを表示
        redirect_to root_path
      end
    else
      redirect_to user_session_path, alert: 'ログインしてください'
    end
  end

  def profile
    if current_user
      @user = current_user # ログインしているユーザーを@userに設定する
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_profile_path, notice: 'プロフィールが更新されました'
    else
      render 'profile'
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :email, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<div class="container">
  <%= render 'shared/side_nav' %>
  <div class="right-contents">
    <center>
     <h2><%= current_user.email %> さんのおみせ一覧</h2>
     <h3><%= link_to '＋新しいおみせを追加する', user_shop_new_user_path(current_user), class: 'btn btn-primary' %></h3>
 
     <% if @shops.any? %>
       <ul class="list-group shop-list">
         <% @shops.each do |shop| %>
           <li class="list-group-item">
             <div class="row">
               <div class="col-md-3">
                 <% if shop.image.present? %>
                   <%= image_tag shop.image.url, class: "shop-img img-thumbnail" %>
                 <% else %>
                   <%= image_tag 'store.jpg', alt: 'デフォルト画像', class: "shop-img img-thumbnail" %>
                 <% end %>
               </div>
               <div class="col-md-9">
                 <h3><%= link_to shop.name, shop_path(shop) %></h3>
               </div>
             </div>
           </li>
         <% end %>
       </ul>
     <% else %>
       <p>おみせは登録されていません</p>
     <% end %>
     
     <h2><%= current_user.email %> さんのメニュー一覧</h2>
     <h3><%= link_to '＋新しいメニューを追加する', new_item_path, class: 'btn btn-primary' %></h3>
     <% if @items.any? %>
      <ul class="list-group item-list">
        <% @items.each do |item| %>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-6">
                <h4><%= link_to item.name, edit_item_path(item.id) %></h4>
                <p><strong>説明:</strong> <%= item.description %></p>
                <p><strong>価格:</strong> <%= item.price %> 円</p>
                <!-- 他のアイテムの情報を表示 -->
              </div>
              <div class="col-md-6">
                <% if item.image.present? %>
                  <%= image_tag item.image.url, class: "item-img img-thumbnail" %>
                <% else %>
                  <%= image_tag 'menu.jpg', alt: 'デフォルト画像', class: "item-img img-thumbnail" %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>メニューはまだ登録されていません</p>
    <% end %><!-- メニュー一覧を表示 -->
  
    </div>
  </div>
  
 
     <%= link_to '戻る', user_dashboard_path %>
   </center>
 </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <%= render 'shared/side_nav' %>
  <div class="right-contents">
    <h2><%= current_user.last_name.presence || "『ニックネーム』" %> さんのマイページ</h2>
      <%= form_for @user, url: user_profile_path, method: :patch, html: { multipart: true } do |f| %>
        <div class="form-group">
          <%= f.label :last_name, "ニックネーム" %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        
        <!-- プロフィール画像のアップロード -->
        <div class="form-group user-img">
          <strong>アイコン</strong>
          <% if @user.image.present? %>
            <%= image_tag @user.image.url, class: "img-thumbnail circle-image" %>
          <% else %>
            <%= image_tag 'icon_user.png', alt: 'デフォルト画像', class: "img-thumbnail circle-image" %>
          <% end %>
          <%= f.file_field :image, class: 'form-control' %>
        </div>
        
        <div class="actions">
          <%= f.submit "更新", class: "btn btn-primary" %>
        </div>
      <% end %>
        
    <h2>「いいね」したメニュー</h2>
    
    
    
        
        
        
  </div>
</div>