config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  
  
  # config/routes.rb
  get '/search_by_location', to: 'home#search_by_location', as: 'search_by_location'

  
  get 'user_dashboard', to: 'users#dashboard', as: :user_dashboard
  get '/users/profile', to: 'users#profile', as: :user_profile
  get '/shops/profile', to: 'shops#profile'
  
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show]

  resources :items do
    post 'favorites', to: 'favorites#create', on: :member
  end
  
  resources :favorites, only: [:create, :destroy]

  resources :users do
    member do
      get :dashboard
      get :shop_new, to: 'shops#new', as: :user_shop_new
      post :shop_create, to: 'shops#create', as: :user_shop_create
      get :item_new, to: 'items#new', as: :user_item_new
    end
  end

  resources :shops do
    resources :events #
    resources :items, only: [:new, :create] 
  end
end

app/views/shared/_side_nav.html.erb
<div class="side-nav">
  <span class="login-links">
    <ul>
      <% if user_signed_in? %>
        <% if current_user.has_role?(:vendor) %>
          <!-- 出店者＝roles:vendor用の side_nav -->
          <li><%= link_to 'おみせ一覧', user_dashboard_path(current_user) %></li>
          <li><%= link_to 'TOPページ', root_path %></li>
          <li>
            <%= form_tag destroy_user_session_path, method: :delete do %>
              <%= submit_tag 'ログアウト' %>
            <% end %>
          </li>
        <% else %>  
          <!-- 一般ユーザー＝roles:nilの side_nav -->
          <li><%= link_to 'TOPページ', root_path %></li>
          <li><%= link_to 'マイページ', user_profile_path(current_user) %></li>
          <li>
            <%= form_tag destroy_user_session_path, method: :delete do %>
              <%= submit_tag 'ログアウト' %>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <!-- 未ログインユーザー用の side_nav -->
        <li><%= link_to 'ユーザーアカウント作成', new_user_registration_path %></li>
        <li><%= link_to 'ユーザーログイン', user_session_path %></li>
        <li><%= link_to '出店者ログイン', user_session_path %></li>
        <li><%= link_to '新規出店希望者はこちら', '#' %></li>
        <li><%= link_to '管理者限定ログイン', rails_admin_path %></li>
      <% end %>
    </ul>
   
  </span>
</div>