config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  
  
  # config/routes.rb
  get '/search_by_location', to: 'home#search_by_location', as: 'search_by_location'

  
  get 'user_dashboard', to: 'users#dashboard', as: :user_dashboard
  get '/users/profile', to: 'users#profile', as: :user_profile
  get '/shops/profile', to: 'shops#profile'
  
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show]

  resources :items do
    post 'favorites', to: 'favorites#create', on: :member
  end
  
  resources :favorites, only: [:create, :destroy]

  resources :users do
    member do
      get :dashboard
      get :shop_new, to: 'shops#new', as: :user_shop_new
      post :shop_create, to: 'shops#create', as: :user_shop_create
      get :item_new, to: 'items#new', as: :user_item_new
    end
  end

  resources :shops do
    resources :events #
    resources :items, only: [:new, :create] 
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :shop
  belongs_to :location
  has_many :event_items # 中間テーブル
  has_many :items, through: :event_items  # 中間テーブル
  
   # カラム名と属性名を一致させる
  attribute :opened_at, :datetime
  attribute :closed_at, :datetime
  attribute :shop_id, :integer
  attribute :location_id, :integer
  attribute :address, :string
  attribute :created_at, :datetime
  attribute :updated_at, :datetime
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
 
  def index
    @events = Event.all
    @event_dates = Event.pluck(:opened_at).uniq # 開催日時の一覧を取得
    
    # フォームから送信された日付範囲を取得
    date_range = params[:date_range]

    # date_rangeが存在する場合のみクエリを実行
    if date_range.present?
      start_date, end_date = date_range.split(' - ')
      @events = Event.where('opened_at >= ? AND opened_at <= ?', Date.parse(start_date), Date.parse(end_date))
    else
      @events = Event.all
    end
    
  end
  
  def show
    @event = Event.find(params[:id])
    @shop = @event.shop # イベントに関連するショップ情報を取得
    @event_items = @event.items # イベントが提供するアイテムのリストを取得
    @shops = Shop.all # すべてのショップを取得
    
  end
  
  def new
    @locations = Location.all
    @shop = Shop.find(params[:shop_id])
    @event = @shop.events.build
    @user_items = current_user.items
    @shops = Shop.all # すべてのショップ情報を取得（任意の場合）
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @event = @shop.events.build(event_params)
    @event.item_ids = params[:event][:item_ids]
    @shops = Shop.all

    if @event.save
      #binding.pry
      redirect_to shop_event_path(@shop, @event), notice: 'イベントが正常に保存されました。'
    else
      #binding.pry
      flash.now[:alert] = @event.errors.full_messages.join(', ')
      render :new
    end
  end
  
  def edit
    @shop = Shop.find(params[:shop_id]) # 必要ならば、店舗を取得
    @event = @shop.events.find(params[:id]) # 店舗内のイベントを取得
    @user_items = current_user.items
    @shops = Shop.all # すべてのショップ情報を取得（任意の場合）
  end

  def update
    @shop = Shop.find(params[:shop_id]) # 必要ならば、店舗を取得
    @event = @shop.events.find(params[:id]) # 店舗内のイベントを取得
  
    if @event.update(event_params)
      redirect_to shop_event_path(@shop, @event), notice: 'イベントが正常に更新されました。'
    else
      flash.now[:alert] = @event.errors.full_messages.join(', ')
      render :edit
    end
  end


  private

  def event_params
  # パラメーターの許可と必要なフィールドの取得
  permitted_params = params.require(:event).permit(:open_date, :open_time, :close_date, :close_time, :location_id, :address, item_ids: [])

  # open_date と open_time を結合して opened_at を生成
  opened_at = "#{permitted_params[:open_date]} #{permitted_params[:open_time]}"
  closed_at = "#{permitted_params[:close_date]} #{permitted_params[:close_time]}"

  # 不要なパラメーターの削除
  permitted_params.delete(:open_date)
  permitted_params.delete(:open_time)
  permitted_params.delete(:close_date)
  permitted_params.delete(:close_time)

  # 修正されたパラメーターを返す
  permitted_params.merge(opened_at: opened_at, closed_at: closed_at)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
 <%= render 'shared/side_nav' %>
 　<%= form_with(model: @event, url: shop_events_path(current_user), method: :post) do |form| %>
  <!-- 他のフォームフィールド -->

  <!-- 日付ピッカーを適用するフォームフィールド -->
  <%= form.label :opened_at %>
  <%= form.text_field :opened_at, class: "datepicker" %>

  <%= form.submit '登録する' %>
<% end %>
</div>

app/views/events/_index.html.erb
<div class="container">
  <div class="col-md-9 right-contents">
    <h2><%= @shop.name %> のイベント一覧</h2>
    <h3><%= link_to '＋新しいイベントを追加する', new_shop_event_path(@shop), class: 'btn btn-primary' %></h3>
    <% if @events.any? %>
      <ul class="list-group">
        <% @events.each do |event| %>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-12"> <!-- 修正: 列のクラスを col-md-6 から col-md-12 に変更 -->
                <strong>開始日時:</strong> <%= event.opened_at %><br>
                <strong>終了日時:</strong> <%= event.closed_at %><br>
                <strong>場所:</strong> <%= event.location.name %><br>
                <strong>住所:</strong> <%= event.address %><br>
                <%= link_to 'イベント詳細', edit_shop_event_path(@shop, event), class: 'btn btn-info' %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>イベントは登録されていません</p>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'shared/side_nav' %>
    </div>
    <div class="col-md-9 right-contents">
      <h2><%= @event.shop.name %><% if @event.opened_at.present? %>の<%= @event.opened_at.strftime('%Y年%-m月%-d日（%A）') %>の<% end %>イベント</h2>

      <%= form_for [@event.shop, @event], url: shop_event_path(@event.shop, @event), method: :put, html: { class: 'form' } do |f| %>
        <div class="card-body">
          <div class="form-group">
            <strong>キャンパス</strong><br>
            <%= f.collection_select :location_id, Location.all, :id, :name, {}, { class: 'form-control' } %>
          </div>
          <div class="form-group">
            <strong>場所</strong><br>
            <%= f.text_field :address, class: "form-control" %>
          </div>
          <div class="form-group">
            <strong>開店時間</strong><br>
            <%= f.datetime_local_field :opened_at, class: "form-control" %>
          </div>
          <div class="form-group">
            <strong>閉店時間</strong><br>
            <%= f.datetime_local_field :closed_at, class: "form-control" %>
          </div>
          <div class="form-group">
            <strong>提供するメニュー</strong><br>
            <% @user_items.each do |item| %>
              <div class="form-check">
                <%= f.check_box :item_ids, { multiple: true }, item.id, nil %>
                <%= f.label "event_item_#{item.id}", item.name %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="card-footer">
          <%= f.submit "更新する", class: "btn btn-primary" %>
          <%= link_to 'イベント詳細ページを確認', shop_event_path(@event), class: 'btn btn-secondary' %>
          <%= link_to '戻る', "#", class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <%= render 'shared/side_nav' %>
  <div class="right-contents">
    <h2><%= @event.shop.name %> の新規イベント登録</h2>

    <%= form_with(model: [@shop, @event], url: shop_events_path(@shop), method: :post) do |form| %>
      <%= form.hidden_field :shop_id, value: @event.shop.id %>
      
      

      <div class="form-group">
        <%= form.label :open_date, 'イベント開催日' %>
        <%= form.date_field :open_date, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :open_time, '開店時間' %>
        <%= form.time_field :open_time, class: 'form-control' %>
      </div>
      
      
      <div class="form-group">
        <%= form.label :close_time, '閉店時間' %>
        <%= form.time_field :close_time, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :location_id, 'キャンパス' %>
        <%= form.collection_select :location_id, @locations, :id, :name, { prompt: '出店するキャンパスを選ぶ' }, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :address, '場所（例：「本部棟2階エントランス」など）' %>
        <%= form.text_area :address, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :item_ids, '提供するメニューを選択' %>
        <% @user_items.each do |item| %>
          <div class="form-check">
            <%= form.check_box :item_ids, { multiple: true }, item.id, nil %>
            <%= form.label "event_item_#{item.id}", item.name %>
          </div>
        <% end %>
      </div>
      

      <%= form.submit '登録する', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <%= render 'shared/side_nav' %>
  <div class="right-contents"> 
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <% if @event.opened_at.present? %>
              <h2><%= @event.shop.name %>の<%= I18n.l(@event.opened_at, format: :long) %>のイベント</h2>
            <% else %>
              <h2><%= @event.shop.name %>のイベント</h2>
            <% end %>
            
          </div>
          <div class="card-body">
            <p><strong>キャンパス:</strong> <%= @event.location.name %></p>
            <p><strong>場所:</strong> <%= @event.address %></p>
            <p><strong>営業日:</strong> <%= I18n.l(@event.opened_at.to_date, format: :long) %></p>
            <p><strong>営業時間:</strong><%= @event.opened_at.strftime('%-H時%M分') %> ～ <%= @event.closed_at.strftime('%-H時%M分') %></p>

            <p><strong>おみせのせつめい:</strong> <%= @event.shop.description %></p>
            <p><strong>提供予定メニュー:</strong></p>
            <div class="card-deck">
              <% @event_items.each do |item| %>
                <div class="card">
                  <% if item.image.present? %>
                    <%= link_to(image_tag(item.image.url, class: "card-img-top"), item_path(item, user_id: current_user)) %>
                  <% else %>
                    <%= link_to(image_tag('menu.jpg', alt: 'デフォルト画像', class: "card-img-top"), item_path(item, user_id: current_user)) %>
                  <% end %>
                  <div class="card-body">
                    <h5 class="card-title"><%= item.name %></h5>
                    <% if item.price.present? %>
                      <p class="card-text">価格: <%= item.price %>円</p>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          
          <div class="card-footer">
            <%= link_to '戻る', class: 'btn btn-secondary' do %>
              <% if current_user.present? %>
                <% if current_user.has_role?(:vendor) %>
                  <%= link_to 'ダッシュボードへ戻る', user_dashboard_path %>
                <% else %>
                  <%= link_to 'TOPページへ戻る', root_path %>
                <% end %>
              <% else %>
                <%= link_to 'TOPページへ戻る', root_path %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>