config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  devise_for :users
  
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  
  
  # config/routes.rb
  get '/search_by_location', to: 'home#search_by_location', as: 'search_by_location'

  
  get 'user_dashboard', to: 'users#dashboard', as: :user_dashboard
  get '/users/profile', to: 'users#profile', as: :user_profile
  get '/shops/profile', to: 'shops#profile'
  
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show]

  resources :items do
    post 'favorites', to: 'favorites#create', on: :member
  end
  
  resources :favorites, only: [:create, :destroy]

  resources :users do
    member do
      get :dashboard
      get :shop_new, to: 'shops#new', as: :user_shop_new
      post :shop_create, to: 'shops#create', as: :user_shop_create
      get :item_new, to: 'items#new', as: :user_item_new
    end
  end

  resources :shops do
    resources :events #
    resources :items, only: [:new, :create] 
  end
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :event_items
  has_many :events, through: :event_items
  has_and_belongs_to_many :shops
  
  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user! # ログイン済みのユーザーだけがアクセスできるようにする

  def index
    @user = current_user
    @items = @user.items
  end

  def show
    @item = Item.find(params[:id])
    @user = @item.user
    @shops = Shop.all # すべてのショップ情報を取得（任意の場合）
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)
    @item.shop_id = params[:item][:shop_id] # shop_id を設定
    
    if @item.save
      redirect_to items_path(@item), notice: 'メニューが作成されました。'
    else
      render :new
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    if @item.destroy
      redirect_to items_path,  status: :see_other, notice: 'メニューが削除されました。'
    else
      redirect_to items_path, status: :see_other, alert: '削除に失敗しました。' 
    end
  end
  
  def edit
    @item = current_user.items.find(params[:id])
    @shops = Shop.all # すべてのショップ情報を取得（任意の場合）
  end

  def update
    @item = current_user.items.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item), notice: 'メニューが更新されました。'
    else
      render :edit
    end
  end

  private

  def item_params
   params.require(:item).permit(:name, :description, :price, :image) # アイテムの属性に合わせて変更
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_index.html.erb
<div class="container">
  <div class="right-contents">
    <h2><%= current_user.email %> のメニュー一覧</h2>
    <h3><%= link_to '＋新しいメニューを追加する', new_item_path, class: 'btn btn-primary' %></h3>
     <% if @items.any? %>
      <ul class="list-group">
        <% @items.each do |item| %>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-6">
                <h4><%= item.name %></h4>
                <p><strong>説明:</strong> <%= item.description %></p>
                <p><strong>価格:</strong> <%= item.price %> 円</p>
                <!-- 他のアイテムの情報を表示 -->
              </div>
              <div class="col-md-6">
                <% if item.image.present? %>
                  <%= image_tag item.image.url, class: "item-img img-thumbnail" %>
                <% else %>
                  <%= image_tag 'default_item_image.jpg', alt: 'デフォルト画像', class: "item-img img-thumbnail" %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>メニューはまだ登録されていません</p>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'shared/side_nav' %>
    </div>
    <div class="col-md-9 right-contents">
      <h2><%= @item.name %> の確認・編集・削除</h2>
      
        <%= form_for @item, url: item_path(@item), method: :patch, html: { class: 'form' } do |f| %>
        <div class="form-group">
          <strong>メニューのなまえ</strong><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <strong>メニューの説明</strong><br>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <strong>価格</strong><br>
          <%= f.number_field :price, class: 'form-control' %>
        </div>
        <div class="form-group">
          <strong>メニューの写真</strong><br>
          <%= f.file_field :image, class: 'form-control' %>
        </div>
        
        <%= f.submit 'メニュー情報を更新する', class: 'btn btn-primary' %>
      <% end %>
      <%= link_to 'このメニューを削除する', item_path(@item), data: {turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>

    </div>
  </div>
</div>
       
  <center>
    <%= link_to '戻る', user_dashboard_path, class: 'btn btn-secondary' %>
  </center>
</div>

app/views/items/new.html.erb
<div class="container">
  <%= render 'shared/side_nav' %>
  <div class="right-contents">
    <h2><%= current_user.email %> さんのメニュー登録</h2>

    <%= form_with(model: @item, url: items_path, method: :post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name, 'メニュー名' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, 'メニューの説明' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price, '価格（円）' %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image, 'メニュー写真' %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

      <%= form.submit '登録する', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'shared/side_nav' %>
    </div>
    <div class="col-md-9 right-contents">
      <h2><%= @item.name %>の詳細</h2>
      
      <div class="card-body">
        <p><strong>メニューのせつめい:</strong> <%= @item.description %></p>
        <p><strong>価格:</strong> <%= @item.price %> 円</p>
        
        <% if @item.image.present? %>
          <div class="item-image">
            <%= image_tag(@item.image.url, class: "img-thumbnail") %>
          </div>
        <% else %>
          <div class="item-image">
            <%= image_tag('menu.jpg', alt: 'デフォルト画像', class: "img-thumbnail") %>
          </div>
        <% end %>

        <!-- いいねボタン -->
        <% if !@item.user == current_user %>
          <%= link_to favorites_item_path(@item, method: :post) do %>
            <%= image_tag('heart-black.png', class: 'heart-img', alt: 'いいね') %>
          <% end %>
        <% else %>
          <%= link_to favorite_path(@item), method: :delete do %>
            <%= image_tag 'heart-red.png', class: 'heart-img' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>